export const lineReports = [
    // 2020
    { year: 2020, labels: "Jan", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Feb", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Mar", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Apr", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "May", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Jun", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Jul", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Aug", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Sep", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Okt", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Nov", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2020, labels: "Des", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },

    // 2022
    { year: 2022, labels: "Jan", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Feb", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Mar", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Apr", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "May", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Jun", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Jul", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Aug", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Sep", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Okt", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Nov", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2022, labels: "Des", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },

    // 2023
    { year: 2023, labels: "Jan", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Feb", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Mar", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Apr", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "May", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Jun", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Jul", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Aug", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Sep", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Okt", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Nov", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2023, labels: "Des", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },

    // 2024
    { year: 2024, labels: "Jan", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Feb", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Mar", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Apr", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "May", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Jun", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Jul", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Aug", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Sep", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Okt", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Nov", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2024, labels: "Des", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },

    // 2025
    { year: 2025, labels: "Jan", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Feb", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Mar", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Apr", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "May", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Jun", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Jul", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 70), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Aug", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 50), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Sep", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 50), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Okt", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 50), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Nov", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 50), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
    { year: 2025, labels: "Des", data: { "5R": Math.floor(Math.random() * 50), "Abnormality": Math.floor(Math.random() * 50), "Safety": Math.floor(Math.random() * 60), "K3": Math.floor(Math.random() * 20) } },
];