import type { ReportData } from "./variables"; // pastikan tipe `ReportData` diimpor

export const tableDataReport = [
    {
        id: "1",
        created_at: "2024-05-01",
        message: "Temuan kebocoran pipa di area workshop",
        location: "Workshop A",
        pic_name: "Suhaimi",
        type: "Safety",
        follow_up: "Guru",
        image: "/img/laporanNew.JPG",
        status: "NotStarted",
    },
    {
        id: "2",
        created_at: "2024-04-28",
        message: "Peralatan tidak tertata rapi setelah praktikum",
        location: "Lab Komputer",
        pic_name: "Heas Priyo",
        type: "5R",
        follow_up: "Siswa",
        image: "/img/laporanNew.JPG",
        status: "InProcess",
    },
    {
        id: "3",
        created_at: "2024-04-25",
        message: "Material bahan praktik tercecer di lantai",
        location: "Workshop B",
        pic_name: "Amalia",
        type: "5R",
        follow_up: "Siswa",
        image: "/img/laporanNew.JPG",
        status: "Complete",
    },
    {
        id: "4",
        created_at: "2024-04-20",
        message: "AC ruangan tidak berfungsi dengan baik",
        location: "Ruang Teori 3",
        pic_name: "Munir",
        type: "Safety",
        follow_up: "Vendor",
        image: "/img/laporanNew.JPG",
        status: "Hold",
    },
    {
        id: "5",
        created_at: "2024-04-20",
        message: "AC ruangan tidak berfungsi dengan baik",
        location: "Ruang Teori 8",
        pic_name: "Tya",
        type: "Abnormality",
        follow_up: "Vendor",
        image: "/img/laporanNew.JPG",
        status: "Complete",
    },
    {
        id: "6",
        created_at: "2024-05-20",
        message: "AC rusak",
        location: "Ruang Teori 4",
        pic_name: "Heas",
        type: "Abnormality",
        follow_up: "Vendor",
        image: "/img/laporanNew.JPG",
        status: "NotStarted",
    },
    {
        id: "7",
        created_at: "2024-06-20",
        message: "AC rusak",
        location: "Ruang Teori 4",
        pic_name: "Heas",
        type: "Safety",
        follow_up: "Vendor",
        image: "/img/laporanNew.JPG",
        status: "InProcess",
    },
    {
        id: "8",
        created_at: "2024-06-20",
        message: "AC rusak",
        location: "Ruang Teori 4",
        pic_name: "Heas",
        type: "Safety",
        follow_up: "Vendor",
        image: "/img/laporanNew.JPG",
        status: "Complete",
    },
    {
        id: "9",
        created_at: "2024-07-20",
        message: "AC rusak",
        location: "Ruang Teori 4",
        pic_name: "Heas",
        type: "Abnormality",
        follow_up: "Vendor",
        image: "/img/laporanNew.JPG",
        status: "Hold",
    },
    {
        id: "10",
        created_at: "2024-07-20",
        message: "AC rusak",
        location: "Ruang Teori 4",
        pic_name: "Heas",
        type: "Abnormality",
        follow_up: "Vendor",
        image: "/img/laporanNew.JPG",
        status: "Hold",
    },
] as ReportData[];